
language: php

php:
  - 5.5.9
  - 5.5
  - 5.6

services:
  - mysql
  - redis-server


before_install: travis_retry composer self-update

install: travis_retry composer install --no-interaction

sudo: false

before_script:
    - cp .env.travis .env 
    - mysql -e 'create database homestead_test;'
    - php artisan key:generate
    - php artisan migrate

script: vendor/bin/phpunit
